system:
    default:
        field_templates:
            - { template: '@ezdesign/ngenhancedlink/field_view.html.twig', priority: 1 }

    admin_group:
        admin_ui_forms:
            content_edit_form_templates:
                - { template: '@ezdesign/ngenhancedlink/field_edit.html.twig', priority: 100 }

        fielddefinition_edit_templates:
            - { template: "@ezdesign/ngenhancedlink/fielddefinition_edit.twig", priority: 100 }

        # not used?
        fielddefinition_settings_templates:
            - { template: '@ezdesign/ngenhancedlink/fielddefinition_settings.html.twig', priority: 100 }
