system:
    default:
        field_templates:
            - { template: '@ibexadesign/ngenhancedlink/content_fields.html.twig', priority: 1 }

        fielddefinition_edit_templates:
            - { template: "@ibexadesign/ngenhancedlink/field_types.html.twig", priority: 100 }

    admin_group:
        admin_ui_forms:
            content_edit:
                form_templates:
                    - { template: '@ibexadesign/ngenhancedlink/content_edit_form_fields.html.twig', priority: 100 }

        fielddefinition_edit_templates:
            - { template: "@ibexadesign/ngenhancedlink/field_types.html.twig", priority: 100 }

        field_templates:
            - { template: '@ibexadesign/ngenhancedlink/content_fields.html.twig', priority: 100 }

        # not used?
        fielddefinition_settings_templates:
            - { template: '@ibexadesign/ngenhancedlink/fielddefinition_settings.html.twig', priority: 100 }
