EnhancedLinkDefinition:
  type: object
  config:
    fields:
      settings:
        type: MatrixFieldDefinitionSettings
        resolve: "@=value.getFieldSettings()"

EnhancedLinkDefinitionSettings:
  type: object
  config:
    fields:
      columns:
        type: "[MatrixFieldDefinitionColumn]"
      minimumRows:
        type: "Int"
        resolve: "@=value['minimum_rows']"

EnhancedLinkDefinitionColumn:
  type: object
  config:
    fields:
      name:
        type: String
      identifier:
        type: String
